#!/bin/bash
read -p "Enter a value : " num 


echo -e "Using for loop\n" 
for (( i = 1 ; i <= 10 ; i++ ))
do
	echo "$i x $num =  $((i*num)) "
done

echo -e "\nUsing While loop\n" 
j=1
while (( j < 10 )) 
do 
	echo "$j x $num =  $((j*num)) "
	((j++))
done 

